name: 'Napptive Catalog push'
author: 'Napptive'
description: 'Push an application into Napptive catalog.'
inputs:
    description: 'Debug flag in commands'
    required: true
    default: false
  applicationPath:
    description: 'The path of the application to be uploaded'
    required: true
  namespace:
    description: 'The namespace where the application is going to be uploaded'
    required: true
  applicationName:
    description: 'The name of the application'
    required: true
  tag:
    description: 'The application version'
    required: true
    default: 'latest'
  playgroundConfigFile:
    description: 'To use a custom YAML file to change the target playground installation'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.debug }}
    - ${{ inputs.applicationPath }}
    - ${{ inputs.namespace }}
    - ${{ inputs.applicationName }}
    - ${{ inputs.tag }}
    - ${{ inputs.playgroundConfigFile }}
branding:
  icon: 'play'  
  color: 'blue'